[[rules]]
name = "blue"
attributes = [
  { name = "Color", value = "Color::BLUE" }
]

[[messages]]
speaker = "Shopkeeper"
message = "Stop! Thief!"

[[messages]]
speaker = "???"
message = "Shit. I gotta run."

[[messages]]
speaker = "???"
message = """
Better head for the {blue:back alley} over there.
Maybe I'll get away in there
"""
